# Generated by Django 4.2 on 2023-05-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prename', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Féminin', 'Féminin'), ('Masculin', 'Masculin')], max_length=100, null=True)),
                ('note', models.TextField()),
                ('cree_nouveau', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
