# Generated by Django 4.2 on 2023-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=100, null=True),
        ),
    ]
